# Setup
title: Help Bed-Stuy
url: http://bedstuybk.com

# Custom vars
github:
  repo: https://github.com/brainbicycle/bedstuybk.com

sass:
  # Where you keep your scss files
  sass_dir: /
  # Where SASS should look for other SCSS
  load_paths:
    - node_modules/
