# Setup
title: Help Crown Heights
# url: http://irace.me/prospect-heights

# Custom vars
github:
  repo: https://github.com/SamTheGeek/crownheights.online

sass:
  # Where you keep your scss files
  sass_dir: /
  # Where SASS should look for other SCSS
  load_paths:
    - node_modules/
